Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# We need to install gensim for this
import gensim
import gensim.corpora as corpora

corpus_89 = [corpus_2008,corpus_2009]
Dict = corpora.Dictionary(corpus_89)
texts = corpus_89

# Term Document Frequency
td = [id2word.doc2bow(text) for text in texts]

print(td)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-19-783528061878>[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0;31m# Term Document Frequency[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m [0mtd[0m [0;34m=[0m [0;34m[[0m[0mid2word[0m[0;34m.[0m[0mdoc2bow[0m[0;34m([0m[0mtext[0m[0;34m)[0m [0;32mfor[0m [0mtext[0m [0;32min[0m [0mtexts[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0;34m[0m[0m
[1;32m     12[0m [0mprint[0m[0;34m([0m[0mtd[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<ipython-input-19-783528061878>[0m in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0;31m# Term Document Frequency[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m [0mtd[0m [0;34m=[0m [0;34m[[0m[0mid2word[0m[0;34m.[0m[0mdoc2bow[0m[0;34m([0m[0mtext[0m[0;34m)[0m [0;32mfor[0m [0mtext[0m [0;32min[0m [0mtexts[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0;34m[0m[0m
[1;32m     12[0m [0mprint[0m[0;34m([0m[0mtd[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'id2word' is not defined
NameError: name 'id2word' is not defined

